In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://int.repositories.cloud.sap/artifactory/api/pypi/deploy-releases-pypi/simple, https://int.repositories.cloud.sap/artifactory/api/pypi/deploy-releases-hyperspace-pypi/simple

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# 1-D Array
ar = np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [5]:
ar.dtype

dtype('int64')

In [9]:
tuple = (1,3,4.5,6.5,7)
ar = np.array(tuple)
ar
ar.dtype

dtype('float64')

In [11]:
tuple2 = (1,'a4534werwerwrwrtewrttqq3sffsgdg','b',4,5)

ar3 = np.array(tuple2)
ar3

array(['1', 'a4534werwerwrwrtewrttqq3sffsgdg', 'b', '4', '5'],
      dtype='<U31')

In [15]:
tuple2 = (1,'abc','b2324324',4,5)

ar3 = np.array(tuple2,dtype = 'U3')
ar3

array(['1', 'abc', 'b23', '4', '5'], dtype='<U3')

In [19]:
# Create 2-D array
ar2D = np.array([[4,2,3,4],[5,6.5,7,8]])
ar2D

array([[4. , 2. , 3. , 4. ],
       [5. , 6.5, 7. , 8. ]])

In [20]:
ar2D.ndim

2

In [21]:
ar2D.size

8

In [22]:
ar2D.shape

(2, 4)

In [23]:
array2 = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [1,1,1]],
                   [[5,5,5],
                    [5,5,5],
                    [5,5,5],
                    [5,5,5]]])
array2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 1, 1]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [24]:
array2.size

24

In [25]:
array2.shape

(2, 4, 3)

In [26]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.shape)
print(a.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
int64
9
(3, 3)
8


In [27]:
ar4 = np.arange(0,11,1)
ar4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ar5 = np.array([[np.arange(0,11,2)],[np.arange(10,21,2)]])
ar5

array([[[ 0,  2,  4,  6,  8, 10]],

       [[10, 12, 14, 16, 18, 20]]])

In [32]:
ar6 = np.arange(0,12,2).reshape(3,2)
ar6

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])